# Profile dành cho GitHub Actions CI
# Disable Redis và các service không cần thiết khi chạy test schema
spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration
      - org.springframework.boot.autoconfigure.data.redis.RedisRepositoriesAutoConfiguration
  data:
    redis:
      host: localhost
      port: 6379
      username: ""
      password: ""
cloudinary:
  url: "cloudinary://mock_api_key:mock_api_secret@mock_cloud_name"
