server:
  port: 8990
spring:
 
  jpa:
   show-sql: true
   properties:
     format_sql: true   

logging:
  level:
    root: INFO
    # Chỉ định package của bạn hiện log chi tiết (DEBUG/TRACE)
    com.graduation.project: DEBUG
    # Ẩn bớt log framework không cần thiết
    org.springframework: WARN
    org.hibernate: WARN
    org.apache.catalina: WARN
