
-- ============================================================
-- V10: STAFF AND INVENTORY
-- Depends on: users, products
-- UUID values are generated by Java @UuidV7
-- ============================================================

-- ============================================================
-- 1 STAFF
-- ============================================================

CREATE TABLE staff (
    id                  UUID PRIMARY KEY,
    user_id             UUID UNIQUE,
    full_name           VARCHAR(150) NOT NULL,
    phone               VARCHAR(20),
    role_type           VARCHAR(50) NOT NULL,
    license_number      VARCHAR(100),
    base_salary         NUMERIC(15,2) NOT NULL DEFAULT 0,
    commission_rate     NUMERIC(5,2) NOT NULL DEFAULT 0,
    is_active           BOOLEAN NOT NULL DEFAULT TRUE,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_staff_user
        FOREIGN KEY (user_id)
        REFERENCES users(id)
        ON DELETE SET NULL,

    CONSTRAINT ck_staff_role_type
        CHECK (
            role_type IN (
                'DOCTOR',
                'RECEPTIONIST',
                'NURSE',
                'GROOMER',
                'CASHIER',
                'WAREHOUSE',
                'SHOP',
                'MANAGER'
            )
        ),

    CONSTRAINT ck_staff_base_salary
        CHECK (base_salary >= 0),

    CONSTRAINT ck_staff_commission_rate
        CHECK (
            commission_rate >= 0
            AND commission_rate <= 100
        )
);

CREATE UNIQUE INDEX ux_staff_phone
    ON staff(phone)
    WHERE phone IS NOT NULL;

CREATE UNIQUE INDEX ux_staff_license_number
    ON staff(license_number)
    WHERE license_number IS NOT NULL;

CREATE INDEX ix_staff_role_active
    ON staff(role_type, is_active);


-- ============================================================
-- 2 STAFF SCHEDULES
-- ============================================================

CREATE TABLE staff_schedules (
    id                  UUID PRIMARY KEY,
    staff_id            UUID NOT NULL,
    work_date           DATE NOT NULL,
    shift_start         TIME NOT NULL,
    shift_end           TIME NOT NULL,
    note                VARCHAR(255),
    created_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_staff_schedules_staff
        FOREIGN KEY (staff_id)
        REFERENCES staff(id)
        ON DELETE CASCADE,

    CONSTRAINT ck_staff_schedule_time
        CHECK (shift_end > shift_start),

    CONSTRAINT uk_staff_schedule
        UNIQUE (
            staff_id,
            work_date,
            shift_start,
            shift_end
        )
);

CREATE INDEX ix_staff_schedules_date
    ON staff_schedules(work_date);

CREATE INDEX ix_staff_schedules_staff_date
    ON staff_schedules(staff_id, work_date);


-- ============================================================
-- 3 SUPPLIERS
-- ============================================================

CREATE TABLE suppliers (
    id                  UUID PRIMARY KEY,
    name                VARCHAR(200) NOT NULL,
    phone               VARCHAR(20),
    email               VARCHAR(150),
    is_active           BOOLEAN NOT NULL DEFAULT TRUE,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT ck_suppliers_email
        CHECK (
            email IS NULL
            OR email ~* '^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}$'
        )
);

CREATE INDEX ix_suppliers_name
    ON suppliers(name);

CREATE INDEX ix_suppliers_active
    ON suppliers(is_active);


-- ============================================================
-- 4 MEDICINES AND MEDICAL SUPPLIES
-- ============================================================

CREATE TABLE medicines (
    id                  UUID PRIMARY KEY,
    name                VARCHAR(200) NOT NULL,
    sku                 VARCHAR(50),
    unit                VARCHAR(30) NOT NULL,
    min_stock           NUMERIC(10,2) NOT NULL DEFAULT 0,
    import_price        NUMERIC(12,2) NOT NULL DEFAULT 0,
    sell_price          NUMERIC(12,2) NOT NULL DEFAULT 0,
    is_active           BOOLEAN NOT NULL DEFAULT TRUE,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT ck_medicines_min_stock
        CHECK (min_stock >= 0),

    CONSTRAINT ck_medicines_import_price
        CHECK (import_price >= 0),

    CONSTRAINT ck_medicines_sell_price
        CHECK (sell_price >= 0)
);

CREATE UNIQUE INDEX ux_medicines_sku
    ON medicines(sku)
    WHERE sku IS NOT NULL;

CREATE INDEX ix_medicines_name
    ON medicines(name);

CREATE INDEX ix_medicines_active
    ON medicines(is_active);


-- ============================================================
-- 5 STOCK BATCHES
-- Exactly one target: medicine OR shop product
-- ============================================================

CREATE TABLE stock_batches (
    id                  UUID PRIMARY KEY,
    medicine_id         UUID,
    product_id          UUID,
    supplier_id         UUID,
    batch_code          VARCHAR(100),
    quantity            NUMERIC(10,2) NOT NULL,
    remaining_qty       NUMERIC(10,2) NOT NULL,
    import_price        NUMERIC(12,2) NOT NULL DEFAULT 0,
    expiry_date         DATE,
    received_at         TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_stock_batches_medicine
        FOREIGN KEY (medicine_id)
        REFERENCES medicines(id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_stock_batches_product
        FOREIGN KEY (product_id)
        REFERENCES products(id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_stock_batches_supplier
        FOREIGN KEY (supplier_id)
        REFERENCES suppliers(id)
        ON DELETE SET NULL,

    CONSTRAINT ck_stock_batches_target
        CHECK (
            (
                medicine_id IS NOT NULL
                AND product_id IS NULL
            )
            OR
            (
                medicine_id IS NULL
                AND product_id IS NOT NULL
            )
        ),

    CONSTRAINT ck_stock_batches_quantity
        CHECK (quantity > 0),

    CONSTRAINT ck_stock_batches_remaining_qty
        CHECK (
            remaining_qty >= 0
            AND remaining_qty <= quantity
        ),

    CONSTRAINT ck_stock_batches_import_price
        CHECK (import_price >= 0)
);

CREATE UNIQUE INDEX ux_stock_batches_medicine_code
    ON stock_batches(medicine_id, batch_code)
    WHERE medicine_id IS NOT NULL
      AND batch_code IS NOT NULL;

CREATE UNIQUE INDEX ux_stock_batches_product_code
    ON stock_batches(product_id, batch_code)
    WHERE product_id IS NOT NULL
      AND batch_code IS NOT NULL;

CREATE INDEX ix_stock_batches_medicine_fefo
    ON stock_batches(medicine_id, expiry_date)
    WHERE medicine_id IS NOT NULL
      AND remaining_qty > 0;

CREATE INDEX ix_stock_batches_product_fefo
    ON stock_batches(product_id, expiry_date)
    WHERE product_id IS NOT NULL
      AND remaining_qty > 0;

CREATE INDEX ix_stock_batches_expiry
    ON stock_batches(expiry_date)
    WHERE expiry_date IS NOT NULL
      AND remaining_qty > 0;

CREATE INDEX ix_stock_batches_supplier
    ON stock_batches(supplier_id);


-- ============================================================
-- 6 STOCK VOUCHERS
-- ============================================================

CREATE TABLE stock_vouchers (
    id                  UUID PRIMARY KEY,
    type                VARCHAR(20) NOT NULL,
    status              VARCHAR(20) NOT NULL DEFAULT 'DRAFT',
    created_by          UUID,
    approved_by         UUID,
    approved_at         TIMESTAMPTZ,
    note                VARCHAR(500),
    created_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_stock_vouchers_created_by
        FOREIGN KEY (created_by)
        REFERENCES staff(id)
        ON DELETE SET NULL,

    CONSTRAINT fk_stock_vouchers_approved_by
        FOREIGN KEY (approved_by)
        REFERENCES staff(id)
        ON DELETE SET NULL,

    CONSTRAINT ck_stock_vouchers_type
        CHECK (
            type IN (
                'IMPORT',
                'EXPORT',
                'TRANSFER',
                'STOCKTAKE'
            )
        ),

    CONSTRAINT ck_stock_vouchers_status
        CHECK (
            status IN (
                'DRAFT',
                'APPROVED',
                'CANCELLED'
            )
        ),

    CONSTRAINT ck_stock_vouchers_approval
        CHECK (
            (
                status = 'APPROVED'
                AND approved_by IS NOT NULL
                AND approved_at IS NOT NULL
            )
            OR status <> 'APPROVED'
        )
);

CREATE INDEX ix_stock_vouchers_status_created
    ON stock_vouchers(status, created_at DESC);

CREATE INDEX ix_stock_vouchers_created_by
    ON stock_vouchers(created_by);


-- ============================================================
-- 7 STOCK VOUCHER ITEMS
-- ============================================================

CREATE TABLE stock_voucher_items (
    id                  UUID PRIMARY KEY,
    voucher_id          UUID NOT NULL,
    batch_id            UUID,
    medicine_id         UUID,
    product_id          UUID,
    quantity            NUMERIC(10,2) NOT NULL,
    unit_price          NUMERIC(12,2),
    note                VARCHAR(255),

    CONSTRAINT fk_stock_voucher_items_voucher
        FOREIGN KEY (voucher_id)
        REFERENCES stock_vouchers(id)
        ON DELETE CASCADE,

    CONSTRAINT fk_stock_voucher_items_batch
        FOREIGN KEY (batch_id)
        REFERENCES stock_batches(id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_stock_voucher_items_medicine
        FOREIGN KEY (medicine_id)
        REFERENCES medicines(id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_stock_voucher_items_product
        FOREIGN KEY (product_id)
        REFERENCES products(id)
        ON DELETE RESTRICT,

    CONSTRAINT ck_stock_voucher_items_target
        CHECK (
            (
                medicine_id IS NOT NULL
                AND product_id IS NULL
            )
            OR
            (
                medicine_id IS NULL
                AND product_id IS NOT NULL
            )
        ),

    CONSTRAINT ck_stock_voucher_items_quantity
        CHECK (quantity > 0),

    CONSTRAINT ck_stock_voucher_items_unit_price
        CHECK (
            unit_price IS NULL
            OR unit_price >= 0
        )
);

CREATE INDEX ix_stock_voucher_items_voucher
    ON stock_voucher_items(voucher_id);

CREATE INDEX ix_stock_voucher_items_batch
    ON stock_voucher_items(batch_id);

CREATE INDEX ix_stock_voucher_items_medicine
    ON stock_voucher_items(medicine_id)
    WHERE medicine_id IS NOT NULL;

CREATE INDEX ix_stock_voucher_items_product
    ON stock_voucher_items(product_id)
    WHERE product_id IS NOT NULL;


-- ============================================================
-- 8 DOCUMENTATION
-- ============================================================

COMMENT ON TABLE stock_batches IS
    'Inventory batches supporting FEFO for medicines and products';

COMMENT ON COLUMN stock_batches.remaining_qty IS
    'Quantity still available; updated transactionally after approved vouchers';

COMMENT ON TABLE stock_vouchers IS
    'Inventory movement document; stock changes only when status becomes APPROVED';
