
-- ============================================================
-- V12: BILLING AND NOTIFICATIONS
-- Depends on:
-- clinic_customers, clinic_pets, clinic_services,
-- products, medicines, staff, users
-- UUID values are generated by Java @UuidV7
-- ============================================================

-- ============================================================
-- 1. INVOICES
-- ============================================================

CREATE TABLE invoices (
    id                  UUID PRIMARY KEY,
    invoice_code        VARCHAR(50) NOT NULL,
    customer_id         UUID NOT NULL,
    pet_id              UUID,
    parent_invoice_id   UUID,
    type                VARCHAR(20) NOT NULL,
    status              VARCHAR(20) NOT NULL DEFAULT 'DRAFT',
    subtotal            NUMERIC(15,2) NOT NULL DEFAULT 0,
    discount_amount     NUMERIC(15,2) NOT NULL DEFAULT 0,
    total_amount        NUMERIC(15,2) NOT NULL DEFAULT 0,
    payment_method      VARCHAR(30),
    paid_at             TIMESTAMPTZ,
    created_by          UUID,
    note                VARCHAR(500),
    created_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uk_invoices_code
        UNIQUE (invoice_code),

    CONSTRAINT fk_invoices_customer
        FOREIGN KEY (customer_id)
        REFERENCES clinic_customers(id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_invoices_pet
        FOREIGN KEY (pet_id)
        REFERENCES clinic_pets(id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_invoices_parent
        FOREIGN KEY (parent_invoice_id)
        REFERENCES invoices(id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_invoices_created_by
        FOREIGN KEY (created_by)
        REFERENCES staff(id)
        ON DELETE SET NULL,

    CONSTRAINT ck_invoices_not_self_parent
        CHECK (
            parent_invoice_id IS NULL
            OR parent_invoice_id <> id
        ),

    CONSTRAINT ck_invoices_type
        CHECK (type IN ('CLINIC', 'SHOP', 'MIXED')),

    CONSTRAINT ck_invoices_status
        CHECK (status IN ('DRAFT', 'PAID', 'CANCELLED')),

    CONSTRAINT ck_invoices_subtotal
        CHECK (subtotal >= 0),

    CONSTRAINT ck_invoices_discount
        CHECK (
            discount_amount >= 0
            AND discount_amount <= subtotal
        ),

    CONSTRAINT ck_invoices_total
        CHECK (
            total_amount >= 0
            AND total_amount = subtotal - discount_amount
        ),

    CONSTRAINT ck_invoices_payment
        CHECK (
            (
                status = 'PAID'
                AND paid_at IS NOT NULL
                AND payment_method IS NOT NULL
            )
            OR
            (
                status <> 'PAID'
                AND paid_at IS NULL
            )
        ),

    CONSTRAINT ck_invoices_payment_method
        CHECK (
            payment_method IS NULL
            OR payment_method IN (
                'CASH',
                'CARD',
                'BANK_TRANSFER',
                'VNPAY',
                'MOMO'
            )
        )
);

CREATE INDEX ix_invoices_customer_created
    ON invoices(customer_id, created_at DESC);

CREATE INDEX ix_invoices_pet_created
    ON invoices(pet_id, created_at DESC)
    WHERE pet_id IS NOT NULL;

CREATE INDEX ix_invoices_status_created
    ON invoices(status, created_at DESC);

CREATE INDEX ix_invoices_parent
    ON invoices(parent_invoice_id)
    WHERE parent_invoice_id IS NOT NULL;


-- ============================================================
-- 2. INVOICE ITEMS
-- Exactly one reference: service, product or medicine
-- ============================================================

CREATE TABLE invoice_items (
    id                  UUID PRIMARY KEY,
    invoice_id          UUID NOT NULL,
    service_id          UUID,
    product_id          UUID,
    medicine_id         UUID,
    name_snapshot       VARCHAR(255) NOT NULL,
    quantity            NUMERIC(10,2) NOT NULL,
    unit_price          NUMERIC(12,2) NOT NULL,
    total               NUMERIC(15,2) NOT NULL,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_invoice_items_invoice
        FOREIGN KEY (invoice_id)
        REFERENCES invoices(id)
        ON DELETE CASCADE,

    CONSTRAINT fk_invoice_items_service
        FOREIGN KEY (service_id)
        REFERENCES clinic_services(id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_invoice_items_product
        FOREIGN KEY (product_id)
        REFERENCES products(id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_invoice_items_medicine
        FOREIGN KEY (medicine_id)
        REFERENCES medicines(id)
        ON DELETE RESTRICT,

    CONSTRAINT ck_invoice_items_reference
        CHECK (
            (service_id IS NOT NULL)::INTEGER
            + (product_id IS NOT NULL)::INTEGER
            + (medicine_id IS NOT NULL)::INTEGER = 1
        ),

    CONSTRAINT ck_invoice_items_name
        CHECK (NULLIF(BTRIM(name_snapshot), '') IS NOT NULL),

    CONSTRAINT ck_invoice_items_quantity
        CHECK (quantity > 0),

    CONSTRAINT ck_invoice_items_unit_price
        CHECK (unit_price >= 0),

    CONSTRAINT ck_invoice_items_total
        CHECK (total >= 0)
);

CREATE INDEX ix_invoice_items_invoice
    ON invoice_items(invoice_id);

CREATE INDEX ix_invoice_items_service
    ON invoice_items(service_id)
    WHERE service_id IS NOT NULL;

CREATE INDEX ix_invoice_items_product
    ON invoice_items(product_id)
    WHERE product_id IS NOT NULL;

CREATE INDEX ix_invoice_items_medicine
    ON invoice_items(medicine_id)
    WHERE medicine_id IS NOT NULL;


-- ============================================================
-- 3. NOTIFICATION TEMPLATES
-- ============================================================

CREATE TABLE notification_templates (
    id                  UUID PRIMARY KEY,
    code                VARCHAR(100) NOT NULL,
    channel             VARCHAR(20) NOT NULL,
    subject             VARCHAR(255),
    body                TEXT NOT NULL,
    is_active           BOOLEAN NOT NULL DEFAULT TRUE,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uk_notification_templates_code
        UNIQUE (code),

    CONSTRAINT ck_notification_templates_channel
        CHECK (
            channel IN (
                'EMAIL',
                'ZNS',
                'SMS',
                'IN_APP'
            )
        ),

    CONSTRAINT ck_notification_templates_body
        CHECK (NULLIF(BTRIM(body), '') IS NOT NULL)
);

CREATE INDEX ix_notification_templates_channel_active
    ON notification_templates(channel, is_active);


-- ============================================================
-- 4. NOTIFICATIONS
-- ============================================================

CREATE TABLE notifications (
    id                  UUID PRIMARY KEY,
    user_id             UUID,
    template_id         UUID,
    channel             VARCHAR(20) NOT NULL,
    recipient           VARCHAR(255),
    title               VARCHAR(255),
    body                TEXT NOT NULL,
    status              VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    attempt_count       INTEGER NOT NULL DEFAULT 0,
    scheduled_at        TIMESTAMPTZ,
    sent_at             TIMESTAMPTZ,
    read_at             TIMESTAMPTZ,
    failure_reason      VARCHAR(500),
    created_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_notifications_user
        FOREIGN KEY (user_id)
        REFERENCES users(id)
        ON DELETE SET NULL,

    CONSTRAINT fk_notifications_template
        FOREIGN KEY (template_id)
        REFERENCES notification_templates(id)
        ON DELETE SET NULL,

    CONSTRAINT ck_notifications_channel
        CHECK (
            channel IN (
                'EMAIL',
                'ZNS',
                'SMS',
                'IN_APP'
            )
        ),

    CONSTRAINT ck_notifications_status
        CHECK (
            status IN (
                'PENDING',
                'PROCESSING',
                'SENT',
                'FAILED',
                'CANCELLED'
            )
        ),

    CONSTRAINT ck_notifications_attempt_count
        CHECK (attempt_count >= 0),

    CONSTRAINT ck_notifications_body
        CHECK (NULLIF(BTRIM(body), '') IS NOT NULL),

    CONSTRAINT ck_notifications_recipient
        CHECK (
            channel = 'IN_APP'
            OR NULLIF(BTRIM(recipient), '') IS NOT NULL
        ),

    CONSTRAINT ck_notifications_sent_at
        CHECK (
            status <> 'SENT'
            OR sent_at IS NOT NULL
        ),

    CONSTRAINT ck_notifications_failure
        CHECK (
            status <> 'FAILED'
            OR NULLIF(BTRIM(failure_reason), '') IS NOT NULL
        )
);

CREATE INDEX ix_notifications_user_created
    ON notifications(user_id, created_at DESC)
    WHERE user_id IS NOT NULL;

CREATE INDEX ix_notifications_pending
    ON notifications(
        COALESCE(scheduled_at, created_at),
        created_at
    )
    WHERE status = 'PENDING';

CREATE INDEX ix_notifications_status_created
    ON notifications(status, created_at);

CREATE INDEX ix_notifications_unread
    ON notifications(user_id, created_at DESC)
    WHERE channel = 'IN_APP'
      AND status = 'SENT'
      AND read_at IS NULL;


-- ============================================================
-- 5. DOCUMENTATION
-- ============================================================

COMMENT ON TABLE invoices IS
    'Clinic, shop or mixed invoices; supports parent-child split invoices';

COMMENT ON COLUMN invoice_items.name_snapshot IS
    'Immutable item name captured when invoice is created';

COMMENT ON TABLE notifications IS
    'Notification outbox supporting retries and scheduled delivery';

COMMENT ON COLUMN notifications.recipient IS
    'Snapshot email address or phone; optional for IN_APP channel';
